site_name: H24 Documentation
repo_url: https://github.com/eighties-cities/h24/
site_url: https://eighties-cities.github.io/h24/
theme:
  name: material
plugins:
  - search
  - macros:
      module_name: docs/macros
markdown_extensions:
    - pymdownx.snippets
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.superfences
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - admonition
nav:
  - Home: index.md
  - h24 library - Workflows : h24workflows.md
  - h24 library - Documentation : h24documentation.md

extra_css:
  - /docs/css/moar.css
