site_name: H24 Documentation
site_url: https://eighties-cities.github.io/h24/
theme:
  name: material
plugins:
  - search
  - macros:
      module_name: docs/macros
markdown_extensions:
    - pymdownx.snippets
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.superfences
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - admonition
nav:
  - Home: index.md
  - Generation: workflow.md
  - About: about.md
extra_css:
  - /docs/css/moar.css
