name: ci
on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install Python dependencies
        run: |
          pip install setuptools wheel
          pip install mkdocs-material
          pip install mkdocs-macros-plugin
          pip install pymdown-extensions
          git clone https://github.com/fschaeck/PythonSed.git
          cd PythonSed && pip install .
      - name: Deploy site
        run: |
          mkdocs gh-deploy --force
          mkdocs --version
